CREATE TABLE IF NOT EXISTS SiteRegionMapping(
SiteId INTEGER,
RegionId INTEGER,
SiteRegionId VARCHAR,
PRIMARY KEY(SiteId,RegionId));
BEGIN;
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1251,'\http://astrakhan-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1281,'\http://www.volgograd-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1282,'\http://realty.volzhskiy-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2659,'\http://realty.volzhskiy-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1336,'\http://realty.makhachkala-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,134,'\http://realty.bryansk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1597,'\http://realty.krasnodar-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1598,'\http://www.sochi-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,179,'\http://vladimir-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1823,'\http://realty.rostov-na-donu-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1827,'\http://realty.volgodonsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1922,'\http://realty.vladikavkaz-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,1952,'\http://realty.stavropol-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2165,'\http://ufa-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2170,'\http://belor-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2173,'\http://realty.sibay-citytar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,218,'\http://www.voroneg-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2257,'\http://realty.kirov-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,330,'\http://realty.kirov-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2371,'\http://www.n-novgorod-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2459,'\http://orenburg-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2513,'\http://www.penza-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2556,'\http://realty.perm-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2633,'\http://www.samara-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2634,'\http://www.tolyati-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2696,'\http://realty.saratov-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2698,'\http://www.balakovo-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2752,'\http://realty.kazan-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2753,'\http://www.naberejnye-chelny-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2807,'\http://realty.izhevsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2840,'\http://realty.ulyanovsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,28755,'\http://realty.moskva-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2876,'\http://cheboksary-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2902,'\http://realty.kurgan-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2931,'\http://realtyekaterinburg.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,2932,'\http://www.ntagil-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,297,'\http://ivanovo-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3044,'\http://tumen-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3045,'\http://realty.surgut-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3140,'\http://realty.surgut-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3046,'\http://realty.nizhnevartovsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3141,'\http://realty.nizhnevartovsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3051,'\http://khanty-mansiysk-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3143,'\http://khanty-mansiysk-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3180,'\http://realty.citystar74.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3181,'\http://realty.magnitogorsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3182,'\http://www.zlatoust-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3183,'\http://www.miass-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3189,'\http://www.chebarkul-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,327,'\http://realty.kaluga-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3275,'\http://www.barnaul-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3357,'\http://realty.ulan-ude-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3400,'\http://realty.chita-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3453,'\http://www.irkutsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3516,'\http://www.novokuzneck-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3517,'\http://realty.kemerovo-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3573,'\http://realty.krasnoyarsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,364,'\http://kostroma-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3651,'\http://realty.novosibirsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,37,'\http://www.spb-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3705,'\http://omsk-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3747,'\http://realty.tomsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3885,'\http://www.vladivostok-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,392,'\http://realty.kursk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,3982,'\http://www.habarovsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,423,'\http://realty.lipetsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,450,'\http://realty.himki-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,653,'\http://realty.orel-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,674,'\http://ryazan-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,707,'\http://realty.smolensk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,775,'\http://tverv-realty.citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,816,'\http://realty.tula-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,861,'\http://realty.yaroslavl-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,890,'\http://realty.arhangelsk-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,92,'\http://realty.belgorod-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,934,'\http://realty.cherepovez-citystar.ru');
INSERT OR REPLACE INTO SiteRegionMapping(SiteId,RegionId,SiteRegionId) VALUES (13,967,'\http://realty.kaliningrad-citystar.ru');
COMMIT;

