CREATE TABLE IF NOT EXISTS SiteRegion(
SiteId INTEGER,
SiteRegionId VARCHAR,
SiteRegionTitle VARCHAR,
ParentId VARCHAR,
Level INTEGER,
PRIMARY KEY(SiteId,SiteRegionId));
BEGIN;
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.arhangelsk-citystar.ru','Архангельск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://astrakhan-realty.citystar.ru','Астрахань','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.balakovo-citystar.ru','Балаково','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.barnaul-citystar.ru','Барнаул','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.belgorod-citystar.ru','Белгород','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://belor-realty.citystar.ru','Белорецк','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.bryansk-citystar.ru','Брянск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.vladivostok-citystar.ru','Владивосток','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.vladikavkaz-citystar.ru','Владикавказ','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://vladimir-realty.citystar.ru','Владимир','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.volgograd-citystar.ru','Волгоград','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.volgodonsk-citystar.ru','Волгодонск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.volzhskiy-citystar.ru','Волжский','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.voroneg-citystar.ru','Воронеж','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realtyekaterinburg.ru','Екатеринбург','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.zlatoust-citystar.ru','Златоуст','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://ivanovo-realty.citystar.ru','Иваново','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.izhevsk-citystar.ru','Ижевск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.irkutsk-citystar.ru','Иркутск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kazan-citystar.ru','Казань','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kaliningrad-citystar.ru','Калининград','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kaluga-citystar.ru','Калуга','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kemerovo-citystar.ru','Кемерово','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kirov-citystar.ru','Киров','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://kostroma-realty.citystar.ru','Кострома','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.krasnodar-citystar.ru','Краснодар','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.krasnoyarsk-citystar.ru','Красноярск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kurgan-citystar.ru','Курган','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.kursk-citystar.ru','Курск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.lipetsk-citystar.ru','Липецк','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.magnitogorsk-citystar.ru','Магнитогорск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.makhachkala-citystar.ru','Махачкала','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.miass-citystar.ru','Миасс','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.moskva-citystar.ru','Москва','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.naberejnye-chelny-citystar.ru','Набережные Челны','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.nizhnevartovsk-citystar.ru','Нижневартовск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.n-novgorod-citystar.ru','Нижний Новгород','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.ntagil-citystar.ru','Нижний Тагил','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.novokuzneck-citystar.ru','Новокузнецк','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.novosibirsk-citystar.ru','Новосибирск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://omsk-realty.citystar.ru','Омск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.orel-citystar.ru','Орел','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://orenburg-realty.citystar.ru','Оренбург','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.penza-citystar.ru','Пенза','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.perm-citystar.ru','Пермь','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.rostov-na-donu-citystar.ru','Ростов-на-Дону','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://ryazan-realty.citystar.ru','Рязань','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.samara-citystar.ru','Самара','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.spb-citystar.ru','Санкт-Петербург','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.saratov-citystar.ru','Саратов','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.sibay-citytar.ru','Сибай','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.smolensk-citystar.ru','Смоленск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.sochi-citystar.ru','Сочи','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.stavropol-citystar.ru','Ставрополь','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.surgut-citystar.ru','Сургут','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://tverv-realty.citystar.ru','Тверь','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.tolyati-citystar.ru','Тольятти','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.tomsk-citystar.ru','Томск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.tula-citystar.ru','Тула','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://tumen-realty.citystar.ru','Тюмень','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.ulan-ude-citystar.ru','Улан-Удэ','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.ulyanovsk-citystar.ru','Ульяновск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://ufa-realty.citystar.ru','Уфа','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.habarovsk-citystar.ru','Хабаровск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://khanty-mansiysk-realty.citystar.ru','Ханты-Мансийск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.himki-citystar.ru','Химки','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://www.chebarkul-citystar.ru','Чебаркуль','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://cheboksary-realty.citystar.ru','Чебоксары','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.citystar74.ru','Челябинск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.cherepovez-citystar.ru','Череповец','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.chita-citystar.ru','Чита','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (13,'\http://realty.yaroslavl-citystar.ru','Ярославль','\',1);
COMMIT;

