rem sqlite3 RealtyParser.sqlite3 < EgentAction.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRubric.sql
rem sqlite3 RealtyParser.sqlite3 < EgentActionMapping.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRubricMapping.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRegion.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRegionMapping1.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRegionMapping1Delete.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRegionMapping2.sql
rem sqlite3 RealtyParser.sqlite3 < EgentRegionDelete.sql
