INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Адыгея Респ\/majjkop','Майкоп','\Россия\Адыгея Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Алтай Респ\/Gorno_Altaisk','Горно-Алтайск','\Россия\Алтай Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Алтайский край\/Barnaul','Барнаул','\Россия\Алтайский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Алтайский край\/Biysk','Бийск','\Россия\Алтайский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Амурская обл\/Blagoveschensk','Благовещенск','\Россия\Амурская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Архангельская обл\/Arkkhangelsk','Архангельск','\Россия\Архангельская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Архангельская обл\/Severodvinsk','Северодвинск','\Россия\Архангельская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Астраханская обл\/Astrakhan','Астрахань','\Россия\Астраханская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Башкортостан Респ\/Salavat','Салават','\Россия\Башкортостан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Башкортостан Респ\/Sterlitamak','Стерлитамак','\Россия\Башкортостан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Башкортостан Респ\/Ufa','Уфа','\Россия\Башкортостан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Белгородская обл\/Belgorod','Белгород','\Россия\Белгородская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Брянская обл\/Bryansk','Брянск','\Россия\Брянская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Бурятия Респ\/Ulan_Ude','Улан-Удэ','\Россия\Бурятия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Владимирская обл\/Vladimir','Владимир','\Россия\Владимирская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Владимирская обл\/Murom','Муром','\Россия\Владимирская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Волгоградская обл\/Volgograd','Волгоград','\Россия\Волгоградская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Волгоградская обл\/Kamyshin','Камышин','\Россия\Волгоградская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Вологодская обл\/Vologda','Вологда','\Россия\Вологодская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Вологодская обл\/Cherepovec','Череповец','\Россия\Вологодская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Воронежская обл\/Voronezh','Воронеж','\Россия\Воронежская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Дагестан Респ\/Makhachkala','Махачкала','\Россия\Дагестан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Еврейская Аобл\/Birobidzhan','Биробиджан','\Россия\Еврейская Аобл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Забайкальский край\/Chita','Чита','\Россия\Забайкальский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ивановская обл\/Ivanovo','Иваново','\Россия\Ивановская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ингушетия Респ\/Nazran','Назрань','\Россия\Ингушетия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Иркутская обл\/Bratsk','Братск','\Россия\Иркутская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Иркутская обл\/Irkutsk','Иркутск','\Россия\Иркутская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Иркутская обл\/Ust_Ilimsk','Усть-Илимск','\Россия\Иркутская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Кабардино-Балкарская Респ\/Nalchik','Нальчик','\Россия\Кабардино-Балкарская Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Калининградская обл\/Kaliningrad','Калининград','\Россия\Калининградская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Калмыкия Респ\/elista','Элиста','\Россия\Калмыкия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Калужская обл\/Kaluga','Калуга','\Россия\Калужская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Калужская обл\/Obninsk','Обнинск','\Россия\Калужская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Камчатский край\/Petropavlovsk_Kamckhatskij','Петропавловск-Камчатский','\Россия\Камчатский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Карачаево-Черкесская Респ\/Cherkessk','Черкесск','\Россия\Карачаево-Черкесская Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Карелия Респ\/Petrozavodsk','Петрозаводск','\Россия\Карелия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Кемеровская обл\/Kemerovo','Кемерово','\Россия\Кемеровская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Кемеровская обл\/Novokuzneck','Новокузнецк','\Россия\Кемеровская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Кемеровская обл\/Prokopevsk','Прокопьевск','\Россия\Кемеровская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Кемеровская обл\/Sheregesh','Шерегеш','\Россия\Кемеровская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Кировская обл\/Kirov','Киров','\Россия\Кировская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Коми Респ\/Vorkuta','Воркута','\Россия\Коми Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Коми Респ\/Syktyvkar','Сыктывкар','\Россия\Коми Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Костромская обл\/Kostroma','Кострома','\Россия\Костромская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Краснодарский край\/Krasnodar','Краснодар','\Россия\Краснодарский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Краснодарский край\/Novorossiysk','Новороссийск','\Россия\Краснодарский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Краснодарский край\/Sochi','Сочи','\Россия\Краснодарский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Красноярский край\/Krasnoyarsk','Красноярск','\Россия\Красноярский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Красноярский край\/Norilsk','Норильск','\Россия\Красноярский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Курганская обл\/Kurgan','Курган','\Россия\Курганская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Курская обл\/Kursk','Курск','\Россия\Курская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Липецкая обл\/Lipeck','Липецк','\Россия\Липецкая обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Магаданская обл\/Magadan','Магадан','\Россия\Магаданская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Марий Эл Респ\/Joshkar_Ola','Йошкар-Ола','\Россия\Марий Эл Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Мордовия Респ\/Saransk','Саранск','\Россия\Мордовия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Москва г\/Vnukovo','Внуково','\Россия\Москва г\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Москва г\/Zelenograd','Зеленоград','\Россия\Москва г\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Москва г\/','Москва','\Россия\Москва г\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Balashikha','Балашиха','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Vidnoe','Видное','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Vnukovo','Внуково','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Volokolamsk','Волоколамск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Voskresensk','Воскресенск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Golicyno','Голицыно','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Gorki_Leninskie','Горки Ленинские','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Gorodische','Городище','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Dzerzhinskij','Дзержинский','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Dmitrov','Дмитров','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Dolgoprudnyj','Долгопрудный','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Domodedovo','Домодедово','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Dubna','Дубна','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Egorevsk','Егорьевск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Zheleznodorozhnyj','Железнодорожный','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Zhukovskij','Жуковский','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Zvenigorod','Звенигород','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Zelenograd','Зеленоград','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Ivanteevka','Ивантеевка','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Istra','Истра','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Klimovsk','Климовск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Klin','Клин','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Kolomna','Коломна','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Konakovo','Конаково','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Korolev','Королев','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Kotelniki','Котельники','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Krasnogorsk','Красногорск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Krasnoznamensk','Краснознаменск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Kupavna','Купавна','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Lobnya','Лобня','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Losino_Petrovskij','Лосино Петровский','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Luhovicy','Луховицы','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Lytkarino','Лыткарино','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Lyubercy','Люберцы','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Malahovka','Малаховка','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Mihnevo','Михнево','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Mozhaisk','Можайск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Mytischi','Мытищи','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Naro_Fominsk','Наро-Фоминск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Nakhabino','Нахабино','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Noginsk','Ногинск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Odincovo','Одинцово','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Orehovo_Zuevo','Орехово-Зуево','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Pavlovskij_Posad','Павловский Посад','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Petrovskoe','Петровское','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Podolsk','Подольск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Protvino','Протвино','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Pushkino','Пушкино','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Ramenskoe','Раменское','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Reutov','Реутов','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Ruza','Руза','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Sergiev_Posad','Сергиев Посад','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Serpuhov','Серпухов','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Solnechnogorsk','Солнечногорск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Staraya_Kupavna','Старая Купавна','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Stupino','Ступино','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Tatischevo','Татищево','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Fryazino','Фрязино','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Himki','Химки','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Chernogolovka','Черноголовка','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Chehov','Чехов','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/Skhatura','Шатура','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/schelkovo','Щелково','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/scherbinka','Щербинка','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/elektrogorsk','Электрогорск','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/elektrostal','Электросталь','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Московская обл\/jubilejnyj','Юбилейный','\Россия\Московская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Мурманская обл\/Murmansk','Мурманск','\Россия\Мурманская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Нижегородская обл\/Dzerzhinsk','Дзержинск','\Россия\Нижегородская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Нижегородская обл\/Nizhnij_Novgorod','Нижний Новгород','\Россия\Нижегородская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Новгородская обл\/Velikij_Novgorod','Великий Новгород','\Россия\Новгородская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Новосибирская обл\/Berdsk','Бердск','\Россия\Новосибирская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Новосибирская обл\/Novosibirsk','Новосибирск','\Россия\Новосибирская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Омская обл\/Omsk','Омск','\Россия\Омская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Оренбургская обл\/Orenburg','Оренбург','\Россия\Оренбургская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Оренбургская обл\/Orsk','Орск','\Россия\Оренбургская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Орловская обл\/Orel','Орел','\Россия\Орловская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Пензенская обл\/Penza','Пенза','\Россия\Пензенская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Пермский край\/Berezniki','Березники','\Россия\Пермский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Пермский край\/Perm','Пермь','\Россия\Пермский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Приморский край\/Vladivostok','Владивосток','\Россия\Приморский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Приморский край\/Nahodka','Находка','\Россия\Приморский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Приморский край\/Ussuriysk','Уссурийск','\Россия\Приморский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Псковская обл\/Pskov','Псков','\Россия\Псковская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ростовская обл\/Novocherkassk','Новочеркасск','\Россия\Ростовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ростовская обл\/Rostov_na_Donu','Ростов-на-Дону','\Россия\Ростовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ростовская обл\/Taganrog','Таганрог','\Россия\Ростовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ростовская обл\/Skhahty','Шахты','\Россия\Ростовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Рязанская обл\/Ryazan','Рязань','\Россия\Рязанская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Самарская обл\/Samara','Самара','\Россия\Самарская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Самарская обл\/Syzran','Сызрань','\Россия\Самарская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Самарская обл\/Tolyatti','Тольятти','\Россия\Самарская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Санкт-Петербург г\/St_Peterburg','Санкт-Петербург','\Россия\Санкт-Петербург г\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Саратовская обл\/Saratov','Саратов','\Россия\Саратовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Саратовская обл\/engels','Энгельс','\Россия\Саратовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Саха /Якутия/ Респ\/yakutsk','Якутск','\Россия\Саха /Якутия/ Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Сахалинская обл\/yuzhno_Sakhalinsk','Южно-Сахалинск','\Россия\Сахалинская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Свердловская обл\/Verhnyaya_Pyshma','Верхняя Пышма','\Россия\Свердловская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Свердловская обл\/Ekaterinburg','Екатеринбург','\Россия\Свердловская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Свердловская обл\/Nizhnij_Tagil','Нижний Тагил','\Россия\Свердловская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Свердловская обл\/Pervouralsk','Первоуральск','\Россия\Свердловская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Северная Осетия - Алания Респ\/Vladikavkaz','Владикавказ','\Россия\Северная Осетия - Алания Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Смоленская обл\/Smolensk','Смоленск','\Россия\Смоленская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ставропольский край\/Mineralnye_Vody','Минеральные Воды','\Россия\Ставропольский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ставропольский край\/Pyatigorsk','Пятигорск','\Россия\Ставропольский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ставропольский край\/Stavropol','Ставрополь','\Россия\Ставропольский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Тамбовская обл\/Tambov','Тамбов','\Россия\Тамбовская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Татарстан Респ\/Kazan','Казань','\Россия\Татарстан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Татарстан Респ\/Naberezhnye_Chelny','Набережные Челны','\Россия\Татарстан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Татарстан Респ\/Nizhnekamsk','Нижнекамск','\Россия\Татарстан Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Тверская обл\/Tver','Тверь','\Россия\Тверская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Томская обл\/Tomsk','Томск','\Россия\Томская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Тульская обл\/Tula','Тула','\Россия\Тульская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Тыва Респ\/Kyzyl','Кызыл','\Россия\Тыва Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Тюменская обл\/Tyumen','Тюмень','\Россия\Тюменская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Удмуртская Респ\/Izhevsk','Ижевск','\Россия\Удмуртская Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ульяновская обл\/Dimitrovgrad','Димитровград','\Россия\Ульяновская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ульяновская обл\/Ulyanovsk','Ульяновск','\Россия\Ульяновская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Хабаровский край\/Komsomolsk_na_Amure','Комсомольск на Амуре','\Россия\Хабаровский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Хабаровский край\/khabarovsk','Хабаровск','\Россия\Хабаровский край\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Хакасия Респ\/Abakan','Абакан','\Россия\Хакасия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ханты-Мансийский - Югра АО\/Nefteyugansk','Нефтеюганск','\Россия\Ханты-Мансийский - Югра АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ханты-Мансийский - Югра АО\/Nizhnevartovsk','Нижневартовск','\Россия\Ханты-Мансийский - Югра АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ханты-Мансийский - Югра АО\/Surgut','Сургут','\Россия\Ханты-Мансийский - Югра АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ханты-Мансийский - Югра АО\/khanty_Mansiysk','Ханты-Мансийск','\Россия\Ханты-Мансийский - Югра АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Челябинская обл\/Zlatoust','Златоуст','\Россия\Челябинская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Челябинская обл\/Kopeisk','Копейск','\Россия\Челябинская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Челябинская обл\/Magnitogorsk','Магнитогорск','\Россия\Челябинская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Челябинская обл\/Chelyabinsk','Челябинск','\Россия\Челябинская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Чеченская Респ\/Groznyj','Грозный','\Россия\Чеченская Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Чувашская - Чувашия Респ\/Cheboksary','Чебоксары','\Россия\Чувашская - Чувашия Респ\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Чукотский АО\/Anadyr','Анадырь','\Россия\Чукотский АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ямало-Ненецкий АО\/Novyj_Urengoj','Новый Уренгой','\Россия\Ямало-Ненецкий АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ямало-Ненецкий АО\/Noyabrsk','Ноябрьск','\Россия\Ямало-Ненецкий АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ямало-Ненецкий АО\/Salekhard','Салехард','\Россия\Ямало-Ненецкий АО\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ярославская обл\/Volzhskij','Волжский','\Россия\Ярославская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ярославская обл\/Rostov','Ростов','\Россия\Ярославская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ярославская обл\/Rybinsk','Рыбинск','\Россия\Ярославская обл\',3);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level)  VALUES (5,'\Россия\Ярославская обл\/yaroslavl','Ярославль','\Россия\Ярославская обл\',3);
