copy /v /y RealtyParser.sqlite3 RosrealtParser.sqlite3
copy /v /y RealtyParser.sqlite3 MirkvartirParser.sqlite3
copy /v /y RealtyParser.sqlite3 EgentParser.sqlite3
copy /v /y RealtyParser.sqlite3 NetAgentaParser.sqlite3
copy /v /y RealtyParser.sqlite3 BnParser.sqlite3
copy /v /y RealtyParser.sqlite3 BeBossParser.sqlite3
copy /v /y RosrealtParser.sqlite3 ..\RealtyParser.Rosrealt\RosrealtParser.sqlite3
copy /v /y MirkvartirParser.sqlite3 ..\RealtyParser.Mirkvartir\MirkvartirParser.sqlite3
copy /v /y EgentParser.sqlite3 ..\RealtyParser.Egent\EgentParser.sqlite3
copy /v /y NetAgentaParser.sqlite3 ..\RealtyParser.NetAgenta\NetAgentaParser.sqlite3
copy /v /y BnParser.sqlite3 ..\RealtyParser.Bn\BnParser.sqlite3
copy /v /y BeBossParser.sqlite3 ..\RealtyParser.BeBoss\BeBossParser.sqlite3
copy /v /y RealtyParser.sqlite3 ..\RealtyParser.Editor\RealtyParser.sqlite3
copy /v /y RosrealtParser.sqlite3 ..\RealtyParser.Editor\RosrealtParser.sqlite3
copy /v /y MirkvartirParser.sqlite3 ..\RealtyParser.Editor\MirkvartirParser.sqlite3
copy /v /y EgentParser.sqlite3 ..\RealtyParser.Editor\EgentParser.sqlite3
copy /v /y NetAgentaParser.sqlite3 ..\RealtyParser.Editor\NetAgentaParser.sqlite3
copy /v /y BnParser.sqlite3 ..\RealtyParser.Editor\BnParser.sqlite3
copy /v /y BeBossParser.sqlite3 ..\RealtyParser.Editor\BeBossParser.sqlite3
