BEGIN;
DELETE FROM SiteBuilderMapping WHERE SiteId<>15;
DELETE FROM SiteReturnFieldMapping WHERE SiteId<>15;
DELETE FROM SiteRubricActionMapping WHERE SiteId<>15;
DELETE FROM SiteRegionRubricMapping WHERE SiteId<>15;
DELETE FROM SiteActionMapping WHERE SiteId<>15;
DELETE FROM SiteRubricMapping WHERE SiteId<>15;
DELETE FROM SiteRegionMapping WHERE SiteId<>15;
DELETE FROM SiteAction WHERE SiteId<>15;
DELETE FROM SiteRubric WHERE SiteId<>15;
DELETE FROM SiteRegion WHERE SiteId<>15;
DELETE FROM Site WHERE SiteId<>15;
COMMIT;
VACUUM;
