INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::','Аренда::Предложение','');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::','Аренда::Спрос','/kvartiri/hires');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::','Посуточная, почасовая, сезонная аренда::','/posutochno');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::Вторичный рынок','Продажа::Предложение','/kvartiri/prodazha');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::Новостройки','Продажа::Предложение','/kvartiri/novostroiki');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::','Продажа::Спрос','/kvartiri/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Дома, коттеджи::','Продажа::Предложение','/kottedzhej');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Дома, коттеджи::','Продажа::Спрос','/kottedzhej/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Дома, коттеджи::','Аренда::Предложение','/kottedzhej/arenda');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Дома, коттеджи::','Аренда::Спрос','/kottedzhej/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Дома, коттеджи::','Посуточная, почасовая, сезонная аренда::','/posutochno/kottedzhi-doma');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Квартиры и комнаты::','Посуточная, почасовая, сезонная аренда::','/posutochno');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Гостиницы::','Посуточная, почасовая, сезонная аренда::','/posutochno/hotel');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::::','Обмен жилья::','/obmen');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Загородная недвижимость::','Продажа::Предложение','/zagorodnaya-nedvizhimost');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Загородная недвижимость::Дачи, сады','Продажа::Предложение','/dachi-sady');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Загородная недвижимость::Дачи, сады','Продажа::Спрос','/dachi-sady/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Загородная недвижимость::Земельные участки','Продажа::Предложение','/uchastkov');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Жилая недвижимость::Загородная недвижимость::Земельные участки','Продажа::Спрос','/uchastkov/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Офисы::','Аренда::Предложение','/ofis');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Офисы::','Аренда::Спрос','/ofis/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Офисы::','Продажа::Предложение','/ofis/prodazha');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Офисы::','Продажа::Спрос','/ofis/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Торговые помещения::','Аренда::Предложение','/torg');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Торговые помещения::','Аренда::Спрос','/torg/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Торговые помещения::','Продажа::Предложение','/torg/prodazha');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Торговые помещения::','Продажа::Спрос','/torg/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Производственные помещения::','Аренда::Предложение','/production');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Производственные помещения::','Аренда::Спрос','/production/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Производственные помещения::','Продажа::Предложение','/production/prodazha');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Производственные помещения::','Продажа::Спрос','/production/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Склады::','Аренда::Предложение','/sklada');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Склады::','Аренда::Спрос','/sklada/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Склады::','Продажа::Предложение','/sklada/prodazha');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Коммерческая недвижимость::Склады::','Продажа::Спрос','/sklada/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Квартиры, апартаменты::','Аренда::Предложение','/foreign-flat');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Квартиры, апартаменты::','Аренда::Спрос','/foreign-flat/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Квартиры, апартаменты::','Продажа::Предложение','/foreign-flat/sale');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Квартиры, апартаменты::','Продажа::Спрос','/foreign-flat/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Дома, таунхаусы::','Аренда::Предложение','/foreign-house');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Дома, таунхаусы::','Аренда::Спрос','/foreign-house/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Дома, таунхаусы::','Продажа::Предложение','/foreign-house/prodazha');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Дома, таунхаусы::','Продажа::Спрос','/foreign-house/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Земельные участки::','Продажа::Предложение','/foreign-sector');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Зарубежная недвижимость::Земельные участки::','Продажа::Спрос','/foreign-sector/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Прочее::Гаражи, парковочные места, стоянки::','Продажа::Предложение','/garazhi');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Прочее::Гаражи, парковочные места, стоянки::','Продажа::Спрос','/garazhi/buy');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Прочее::Гаражи, парковочные места, стоянки::','Аренда::Предложение','/garazhi/arenda');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Прочее::Гаражи, парковочные места, стоянки::','Аренда::Спрос','/garazhi/hire');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Прочее::Услуги::','Всё::','/uslugi');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Прочее::Другое::','Всё::','/other');
INSERT OR REPLACE INTO SiteRubricActionMapping(SiteId,SiteRubricId,SiteActionId,SiteRubricActionId) VALUES (5,'Вся недвижимость одной страницей::::','Всё::','/nedvizhimost');
