CREATE TABLE IF NOT EXISTS SiteRegion(
SiteId INTEGER,
SiteRegionId VARCHAR,
SiteRegionTitle VARCHAR,
ParentId VARCHAR,
Level INTEGER,
PRIMARY KEY(SiteId,SiteRegionId));
BEGIN;
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3160\','Алтайский край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3223\','Амурская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3251\','Архангельская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3282\','Астраханская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3352\','Белгородская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3371\','Брянская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\','Владимирская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3468\','Волгоградская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3503\','Вологодская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3529\','Воронежская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3673\','Еврейская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3675\','Ивановская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3703\','Иркутская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3751\','Кабардино-Балкарская Республика','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3761\','Калининградская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3841\','Калужская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3872\','Камчатский Край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3921\','Кемеровская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3952\','Кировская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4026\','Костромская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\','Краснодарский край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4105\','Красноярский край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4176\','Курганская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4198\','Курская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4227\','Липецкая область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4243\','Магаданская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\','Московская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4481\','Мурманская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3563\','Нижегородская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4503\','Новгородская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4528\','Новосибирская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4561\','Омская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4593\','Оренбургская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4633\','Орловская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4657\','Пензенская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4689\','Пермская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4734\','Приморский край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4773\','Псковская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\1998532\','Республика Адыгея','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3296\','Республика Башкортостан','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3407\','Республика Бурятия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3630\','Республика Дагестан','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3827\','Республика Калмыкия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3892\','Республика Карелия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3994\','Республика Коми','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4270\','Республика Марий Эл','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4287\','Республика Мордовия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5011\','Республика Саха (Якутия)','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5246\','Республика Татарстан','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2316497\','Республика Хакасия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\','Ростовская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4861\','Рязанская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4891\','Самарская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\','Санкт-Петербург и область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4969\','Саратовская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5052\','Сахалинская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5080\','Свердловская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5151\','Северная Осетия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5161\','Смоленская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5191\','Ставропольский край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5225\','Тамбовская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\','Тверская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5291\','Томская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5312\','Тувинская Республика','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5326\','Тульская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5356\','Тюменская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5404\','Удмуртская Республика','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5432\','Ульяновская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5458\','Уральская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5473\','Хабаровский край','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2499002\','Ханты-Мансийский автономный округ','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5507\','Челябинская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5543\','Чечено-Ингушетия','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5555\','Читинская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5600\','Чувашская республика','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2415585\','Чукотский автономный округ','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5019394\','Ямало-Ненецкий автономный округ','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5625\','Ярославская область','\\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3160\http://barnaul.egent.ru','Барнаул','\3160\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3223\http://blagoveshensk.egent.ru','Благовещенск','\3223\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3251\http://arhangelsk.egent.ru','Архангельск','\3251\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3251\http://solovki.egent.ru','Соловки','\3251\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3282\http://astrahan.egent.ru','Астрахань','\3282\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3352\http://belgorod.egent.ru','Белгород','\3352\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3352\http://stariy-oskol.egent.ru','Старый Оскол','\3352\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3371\http://bryansk.egent.ru','Брянск','\3371\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\http://vladimir.egent.ru','Владимир','\3437\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\http://aleksandrov.egent.ru','Александров','\3437\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\http://gorohovets.egent.ru','Гороховец','\3437\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\http://murom.egent.ru','Муром','\3437\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\http://pokrov.egent.ru','Покров','\3437\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3437\http://suzdal.egent.ru','Суздаль','\3437\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3468\http://velikij-ustjug.egent.ru','Великий Устюг','\3468\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3468\http://volgograd.egent.ru','Волгоград','\3468\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3468\http://kirillov.egent.ru','Кириллов','\3468\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3468\http://totma.egent.ru','Тотьма','\3468\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3468\http://cherepovets.egent.ru','Череповец','\3468\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3503\http://vologda.egent.ru','Вологда','\3503\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3529\http://voroneg.egent.ru','Воронеж','\3529\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3675\http://ivanovo.egent.ru','Иваново','\3675\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3675\http://paleh.egent.ru','Палех','\3675\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3675\http://ples.egent.ru','Плес','\3675\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3703\http://angarsk.egent.ru','Ангарск','\3703\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3703\http://bratsk.egent.ru','Братск','\3703\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3703\http://irkutsk.egent.ru','Иркутск','\3703\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3751\http://nalchik.egent.ru','Нальчик','\3751\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3761\http://kaliningrad.egent.ru','Калининград','\3761\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3841\http://borovsk.egent.ru','Боровск','\3841\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3841\http://kaluga.egent.ru','Калуга','\3841\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3841\http://obninsk.egent.ru','Обнинск','\3841\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3841\http://tarusa.egent.ru','Таруса','\3841\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3872\http://petropavlovsk.egent.ru','Петропавловск-Камчатский','\3872\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3921\http://kemerovo.egent.ru','Кемерово','\3921\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3921\http://novokuznetsk.egent.ru','Новокузнецк','\3921\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3952\http://kirov.egent.ru','Киров','\3952\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4026\http://kostroma.egent.ru','Кострома','\4026\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://anapa.egent.ru','Анапа','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://armavir.egent.ru','Армавир','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://arhipo-osipovka.egent.ru','Архипо-Осиповка','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://gelendzhik.egent.ru','Геленджик','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://gulkevichina.egent.ru','Гулькевичина','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://ejsk.egent.ru','Ейск','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://kabardinka.egent.ru','Кабардинка','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://krasnaja-poljana.egent.ru','Красная поляна','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://krasnodar.egent.ru','Краснодар','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://labinsk.egent.ru','Лабинск','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://lazarevskoe.egent.ru','Лазаревское','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://novorossijsk.egent.ru','Новороссийск','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://sochi.egent.ru','Сочи','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://tuapse.egent.ru','Туапсе','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4052\http://hosta.egent.ru','Хоста','\4052\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4105\http://krasnoyarsk.egent.ru','Красноярск','\4105\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4198\http://kursk.egent.ru','Курск','\4198\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4227\http://elets.egent.ru','Елец','\4227\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4227\http://lipetsk.egent.ru','Липецк','\4227\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://www.egent.ru','Москва','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://akovo.egent.ru','Аково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://aksenovo.egent.ru','Аксеново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://alabino.egent.ru','Алабино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://alabushevo.egent.ru','Алабушево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://aleevo.egent.ru','Алеево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://aleksandrovo.egent.ru','Александрово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://almetevsk.egent.ru','Альметьевск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://andreevka.egent.ru','Андреевка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://antonovo.egent.ru','Антоново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://aprelevka.egent.ru','Апрелевка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://afanasovo-1.egent.ru','Афанасово-1','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bakeevo.egent.ru','Бакеево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bakovka.egent.ru','Баковка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://balakovo.egent.ru','Балаково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://balashiha.egent.ru','Балашиха','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://barviha.egent.ru','Барвиха','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bezobrazovo.egent.ru','Безобразово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://biserovo-ribolovskiy-so-.egent.ru','Бисерово (Рыболовский с/о)','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bittsa.egent.ru','Битца','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bogachevo.egent.ru','Богачево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bolshevo.egent.ru','Болшево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bolshie-dvori.egent.ru','Большие Дворы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://borodki.egent.ru','Бородки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://borozda.egent.ru','Борозда','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://brehovo.egent.ru','Брехово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bronnitsi.egent.ru','Бронницы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bugri.egent.ru','Бугры','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://burtsevo.egent.ru','Бурцево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://butovo.egent.ru','Бутово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://bikovo.egent.ru','Быково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://vatutinki.egent.ru','Ватутинки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://vereya.egent.ru','Верея','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://vidnoe.egent.ru','Видное','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://vniissok.egent.ru','ВНИИССОК','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://vnukovo.egent.ru','Внуково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://voeykovo.egent.ru','Воейково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://voljsky.egent.ru','Волжский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://volodarskiy.egent.ru','Володарский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://volokolamsk.egent.ru','Волоколамск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://voronino.egent.ru','Воронино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://voskresensk.egent.ru','Воскресенск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://vostochniy.egent.ru','Восточный','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://virubovo.egent.ru','Вырубово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://visokovo.egent.ru','Высоково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://visokovsk.egent.ru','Высоковск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://gavrilovskoe.egent.ru','Гавриловское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://govorovo.egent.ru','Говорово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://golitsino.egent.ru','Голицыно','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://goluboe.egent.ru','Голубое','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://gorodok-pisateley.egent.ru','Городок Писателей','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://goryachevodskiy.egent.ru','Горячеводский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://davidovo-davidovskoe-sp-.egent.ru','Давыдово (Давыдовское с/п)','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://darino.egent.ru','Дарьино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://devyatskoe-mkr-rodniki.egent.ru','Девятское мкр Родники','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dedovsk.egent.ru','Дедовск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dzerzhinsky.egent.ru','Дзержинский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dmitrov.egent.ru','Дмитров','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dolgoprudniy.egent.ru','Долгопрудный','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://domodedovo.egent.ru','Домодедово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://drezna.egent.ru','Дрезна','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://droggino.egent.ru','Дрожжино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dsk-michurinets.egent.ru','дск Мичуринец','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dubna.egent.ru','Дубна','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dubovoe.egent.ru','Дубовое','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dubrovki.egent.ru','Дубровки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://dubrovskoe.egent.ru','Дубровское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://egorevsk.egent.ru','Егорьевск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://elino.egent.ru','Елино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://eremino.egent.ru','Еремино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ermolino-oph.egent.ru','Ермолино ОПХ','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://esino.egent.ru','Есино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zhavoronki.egent.ru','Жаворонки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zheleznodorozhnyy.egent.ru','Железнодорожный','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zhitnevo.egent.ru','Житнево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zhukovka.egent.ru','Жуковка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zhukovskiy.egent.ru','Жуковский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zavodoukovsk.egent.ru','Заводоуковск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zagoryanskiy.egent.ru','Загорянский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zaraysk.egent.ru','Зарайск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zaramene.egent.ru','Зараменье','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zareche.egent.ru','Заречье','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zvenigorod.egent.ru','Звенигород','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zvyagino.egent.ru','Звягино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zelenograd.egent.ru','Зеленоград','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zelenogradskiy.egent.ru','Зеленоградский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://zeleniy-gorodok.egent.ru','Зеленый Городок','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ivanovka.egent.ru','Ивановка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ivanteevka.egent.ru','Ивантеевка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ignatovo.egent.ru','Игнатово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://iksha.egent.ru','Икша','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ilinskiy.egent.ru','Ильинский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://istra.egent.ru','Истра','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kaltino.egent.ru','Кальтино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kashira.egent.ru','Кашира','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kineshma.egent.ru','Кинешма','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://klimovsk.egent.ru','Климовск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://klin.egent.ru','Клин','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://klyazma.egent.ru','Клязьма','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kozhuhovo.egent.ru','Кожухово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kolomna.egent.ru','Коломна','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kolichevo.egent.ru','Колычево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://korolev.egent.ru','Королев','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://koryazhma.egent.ru','Коряжма','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kosino-uhtomskiy.egent.ru','Косино-Ухтомский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kotelniki.egent.ru','Котельники','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kraskovo.egent.ru','Красково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://krasnaya-gorka.egent.ru','Красная Горка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://krasnogorsk.egent.ru','Красногорск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://krasnozavodsk.egent.ru','Краснозаводск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://krasnoznamensk.egent.ru','Краснознаменск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://krasniy-holm.egent.ru','Красный Холм','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kratovo.egent.ru','Кратово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kryukovo.egent.ru','Крюково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kubinka.egent.ru','Кубинка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kudrovo.egent.ru','Кудрово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kurkino.egent.ru','Куркино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kurovskoe.egent.ru','Куровское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://kutuzovo.egent.ru','Кутузово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lapino.egent.ru','Лапино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://levkovo.egent.ru','Левково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://leoniha.egent.ru','Леониха','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lesnoy-gorodok.egent.ru','Лесной Городок','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lesnie-polyani.egent.ru','Лесные Поляны','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://likino-dulevo.egent.ru','Ликино-Дулево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lipki.egent.ru','Липки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lobnya.egent.ru','Лобня','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://losino-petrovskiy.egent.ru','Лосино-Петровский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lukino.egent.ru','Лукино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lunevo.egent.ru','Лунево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lupanovo.egent.ru','Лупаново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://luhovitsi.egent.ru','Луховицы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://litkarino.egent.ru','Лыткарино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lvovskiy.egent.ru','Львовский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lyubertsy.egent.ru','Люберцы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lubertsy-2.egent.ru','Люберцы-2','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://lyudyatino.egent.ru','Людятино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://malahovka.egent.ru','Малаховка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://malino.egent.ru','Малино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://maloe-sareevo.egent.ru','Малое Сареево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mamonovo.egent.ru','Мамоново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mamontovka.egent.ru','Мамонтовка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://marusino.egent.ru','Марусино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://marushkino.egent.ru','Марушкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://marfino.egent.ru','Марфино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://matveykovo.egent.ru','Матвейково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://medvezhi-ozera.egent.ru','Медвежьи Озера','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://meshherskiy.egent.ru','Мещерский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mikishkino.egent.ru','Микишкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://militseyskiy.egent.ru','Милицейский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://minino.egent.ru','Минино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mihnevo.egent.ru','Михнево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mozhaysk.egent.ru','Можайск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://molzhaninovskiy.egent.ru','Молжаниновский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://monino.egent.ru','Монино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://moskovskiy.egent.ru','Московский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mosrentgen-pos.egent.ru','Мосрентген пос','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://murino.egent.ru','Мурино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mytischi.egent.ru','Мытищи','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://mishetskoe.egent.ru','Мышецкое','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://myakinino.egent.ru','Мякинино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nazarovo.egent.ru','Назарово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nazarevo.egent.ru','Назарьево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://naro-fominsk.egent.ru','Наро-Фоминск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nekrasovsky.egent.ru','Некрасовский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nemchinovka.egent.ru','Немчиновка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nikolo-uryupino.egent.ru','Николо-Урюпино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nikolsko-arhangelskiy.egent.ru','Никольско-Арх-кий','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nikonovo.egent.ru','Никоново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novlyanskoe.egent.ru','Новлянское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novo-peredelkino.egent.ru','Ново-Переделкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novoglagolevo.egent.ru','Новоглаголево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novogorsk.egent.ru','Новогорск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novoe-devyatkino.egent.ru','Новое Девяткино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novoivanovskoe.egent.ru','Новоивановское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novopodrezkovo.egent.ru','Новоподрезково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novoselki.egent.ru','Новоселки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://novouralsk.egent.ru','Новоуральск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://noginsk.egent.ru','Ногинск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://obuhovo.egent.ru','Обухово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://obushkovo.egent.ru','Обушково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://odintsovo.egent.ru','Одинцово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ozherele.egent.ru','Ожерелье','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ozhigovo.egent.ru','Ожигово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ozeri.egent.ru','Озеры','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://opaliha.egent.ru','Опалиха','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://orehovo-zuevo.egent.ru','Орехово-Зуево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://orlovo.egent.ru','Орлово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://osinovo.egent.ru','Осиново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ostrovtsi.egent.ru','Островцы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pavlovskaya-sloboda.egent.ru','Павловская Слобода','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pavlovskiy-posad.egent.ru','Павловский Посад','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://padikovo.egent.ru','Падиково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://palitsi.egent.ru','Палицы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pervomayskiy.egent.ru','Первомайский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://peresvet.egent.ru','Пересвет','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pereslavl.egent.ru','Переславль-Залесский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://petrovskoe.egent.ru','Петровское (Ивановский с/о)','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pirogovo.egent.ru','Пирогово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pirochi.egent.ru','Пирочи','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://povarovka.egent.ru','Поваровка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://podolsk.egent.ru','Подольск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://podushkino.egent.ru','Подушкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pozdnyakovo.egent.ru','Поздняково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://polivanovo.egent.ru','Поливаново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://poltevo.egent.ru','Полтево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://poroshkino.egent.ru','Порошкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://potapovo.egent.ru','Потапово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pravdinsky.egent.ru','Правдинский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pronskoe.egent.ru','Пронское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://protvino.egent.ru','Протвино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://purshevo.egent.ru','Пуршево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://putilkovo.egent.ru','Путилково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pushkino.egent.ru','Пушкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pushchino.egent.ru','Пущино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://pyatigorskaya.egent.ru','Пятигорская','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://radiotsentr-9.egent.ru','Радиоцентр-9','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://razdory.egent.ru','Раздоры','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ramenskoe.egent.ru','Раменское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rassudovo.egent.ru','Рассудово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://reutov.egent.ru','Реутов','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rozhdestveno.egent.ru','Рождествено','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://romantsevo.egent.ru','Романцево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://romashkovo.egent.ru','Ромашково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://roshal.egent.ru','Рошаль','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rublevo.egent.ru','Рублево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rubtsovsk.egent.ru','Рубцовск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rubtsovsk.egent.ru','Рубцовск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://ruza.egent.ru','Руза','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rumyantsevo.egent.ru','Румянцево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rusavkino-romanovo.egent.ru','Русавкино-Романово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://rybaki.egent.ru','Рыбаки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://saburovo.egent.ru','Сабурово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://selevino.egent.ru','Селевино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://selskaya-nov.egent.ru','Сельская Новь','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://semkino.egent.ru','Семкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sergiev-posad.egent.ru','Сергиев Посад','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://serednevo.egent.ru','Середнево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://serpuhov.egent.ru','Серпухов','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://skurygino.egent.ru','Скурыгино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://soboliha.egent.ru','Соболиха','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sovhoz-pobeda.egent.ru','Совхоз Победа','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sokolovo.egent.ru','Соколово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sokolovskiy.egent.ru','Соколовский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://solnechnogorsk.egent.ru','Солнечногорск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://solnechnogorsk-7.egent.ru','Солнечногорск-7','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://solntsevo.egent.ru','Солнцево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sofrino.egent.ru','Софрино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sofino.egent.ru','Софьино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://staronikolskoe.egent.ru','Староникольское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://starosemeykino.egent.ru','Старосемейкино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://stepanovo.egent.ru','Степаново','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://sterlitamak.egent.ru','Стерлитамак','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://stroitel.egent.ru','Строитель','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://stupino.egent.ru','Ступино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://suhanovo.egent.ru','Суханово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://shodnya.egent.ru','Сходня','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://tavatuy.egent.ru','Таватуй','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://taganovo.egent.ru','Таганово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://taldom.egent.ru','Талдом','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://talitsi.egent.ru','Талицы','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://tarasovka.egent.ru','Тарасовка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://tekstilshchik.egent.ru','Текстильщик','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://tokarevo.egent.ru','Токарево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://toksovo.egent.ru','Токсово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://tolstopaltsevo.egent.ru','Толстопальцево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://tomilino.egent.ru','Томилино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://trehgorka.egent.ru','Трехгорка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://troitsk.egent.ru','Троицк','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://troitskoe.egent.ru','Троицкое','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://trudovaya.egent.ru','Трудовая','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://udelnaya.egent.ru','Удельная','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://usovo.egent.ru','Усово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://uspenskoe.egent.ru','Успенское','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://uhtomskiy.egent.ru','Ухтомский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://fedyukovo.egent.ru','Федюково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://firsanovka.egent.ru','Фирсановка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://fryazino.egent.ru','Фрязино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://himki.egent.ru','Химки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://hlopovo.egent.ru','Хлопово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://hlistovo.egent.ru','Хлыстово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://hotkovo.egent.ru','Хотьково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chapaevka.egent.ru','Чапаевка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chelyuskinskiy.egent.ru','Челюскинский','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://cherkizovo.egent.ru','Черкизово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chernaya-gryaz.egent.ru','Черная Грязь','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chernigolovka.egent.ru','Черниголовка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chehov.egent.ru','Чехов','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chiverevo.egent.ru','Чиверево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://chirikovo.egent.ru','Чириково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://shatura.egent.ru','Шатура','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://shulgino.egent.ru','Шульгино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://shushari.egent.ru','Шушары','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://shchapovo.egent.ru','Щапово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://schelkovo.egent.ru','Щелково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://scherbinka.egent.ru','Щербинка','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://shchyolkovo.egent.ru','Щёлково','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://elektrogorsk.egent.ru','Электрогорск','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://elektrostal.egent.ru','Электросталь','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://elektrougli.egent.ru','Электроугли','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yubileyniy.egent.ru','Юбилейный','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yukki.egent.ru','Юкки','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yunost.egent.ru','Юность','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yurovo.egent.ru','Юрово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yurevo.egent.ru','Юрьево','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yusupovo.egent.ru','Юсупово','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yarovoe.egent.ru','Яровое','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yahroma.egent.ru','Яхрома','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://nahabino.egent.ru','Нахабино','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4312\http://yanino.egent.ru','Янино-1','\4312\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4481\http://murmansk.egent.ru','Мурманск','\4481\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3563\http://arzamas.egent.ru','Арзамас','\3563\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3563\http://gorodets.egent.ru','Городец','\3563\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3563\http://dzerzhinsk.egent.ru','Дзержинск','\3563\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3563\http://kstovo.egent.ru','Кстово','\3563\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3563\http://nigniy-novgorod.egent.ru','Нижний Новгород','\3563\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4503\http://valdaj.egent.ru','Валдай','\4503\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4503\http://velikij-novgorod.egent.ru','Великий Новгород','\4503\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4528\http://novosibirsk.egent.ru','Новосибирск','\4528\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4561\http://omsk.egent.ru','Омск','\4561\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4593\http://buzuluk.egent.ru','Бузулук','\4593\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4593\http://orenburg.egent.ru','Оренбург','\4593\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4633\http://orel.egent.ru','Орел','\4633\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4657\http://penza.egent.ru','Пенза','\4657\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4689\http://kungur.egent.ru','Кунгур','\4689\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4689\http://perm.egent.ru','Пермь','\4689\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4734\http://vladivostok.egent.ru','Владивосток','\4734\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4734\http://ussuriysk.egent.ru','Уссурийск','\4734\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4773\http://izborsk.egent.ru','Изборск','\4773\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4773\http://pskov.egent.ru','Псков','\4773\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4773\http://pushkinskie-gory.egent.ru','Пушкинские горы','\4773\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\1998532\http://maykop.egent.ru','Майкоп','\1998532\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3296\http://ufa.egent.ru','Уфа','\3296\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3407\http://ulan-ude.egent.ru','Улан-Удэ','\3407\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3630\http://mahachkala.egent.ru','Махачкала','\3630\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3827\http://elista.egent.ru','Элиста','\3827\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3892\http://petrozavodsk.egent.ru','Петрозаводск','\3892\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3892\http://sortavala.egent.ru','Сортавала','\3892\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3994\http://vorkuta.egent.ru','Воркута','\3994\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3994\http://uhta.egent.ru','Ухта','\3994\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4270\http://volzhsk.egent.ru','Волжск','\4270\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4270\http://joshkar-ola.egent.ru','Йошкар-Ола','\4270\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4287\http://saransk.egent.ru','Саранск','\4287\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5246\http://elabuga.egent.ru','Елабуга','\5246\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5246\http://kazan.egent.ru','Казань','\5246\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5246\http://naberezhnye-chelny.egent.ru','Набережные Челны','\5246\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5246\http://nizhnekamsk.egent.ru','Нижнекамск','\5246\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2316497\http://abakan.egent.ru','Абакан','\2316497\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\http://adler.egent.ru','Адлер','\4800\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\http://azov.egent.ru','Азов','\4800\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\http://bataysk.egent.ru','Батайск','\4800\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\http://volgodonsk.egent.ru','Волгодонск','\4800\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\http://rostov-na-donu.egent.ru','Ростов-на-Дону','\4800\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4800\http://taganrog.egent.ru','Таганрог','\4800\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4861\http://ryazan.egent.ru','Рязань','\4861\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4891\http://novokuibyshevsk.egent.ru','Новокуйбышевск','\4891\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4891\http://samara.egent.ru','Самара','\4891\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4891\http://tolyatti.egent.ru','Тольятти','\4891\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://vsevolozhsk.egent.ru','Всеволожск','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://kirovsk.egent.ru','Кировск','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://kolpino.egent.ru','Колпино','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://kronshtadt.egent.ru','Кронштадт','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://lomonosov.egent.ru','Ломоносов','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://pavlovsk.egent.ru','Павловск','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://primorsk.egent.ru','Приморск','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://sertolovo.egent.ru','Сертолово','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://sestroretsk.egent.ru','Сестрорецк','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://tosno.egent.ru','Тосно','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://spb.egent.ru','Санкт-Петербург','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://vyborg.egent.ru','Выборг','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://gatchina.egent.ru','Гатчина','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://petergof.egent.ru','Петергоф','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://priozersk.egent.ru','Приозерск','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://pushkin.egent.ru','Пушкин','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://strelna.egent.ru','Стрельна','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4925\http://shushary.egent.ru','Шушары','\4925\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4969\http://saratov.egent.ru','Саратов','\4969\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\4969\http://engels.egent.ru','Энгельс','\4969\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5080\http://ekaterinburg.egent.ru','Екатеринбург','\5080\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5080\http://nigniy-tagil.egent.ru','Нижний Тагил','\5080\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5161\http://vjazma.egent.ru','Вязьма','\5161\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5161\http://smolensk.egent.ru','Смоленск','\5161\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5191\http://zheleznovodsk.egent.ru','Железноводск','\5191\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5191\http://kislovodsk.egent.ru','Кисловодск','\5191\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5191\http://pjatigorsk.egent.ru','Пятигорск','\5191\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5191\http://stavropol.egent.ru','Ставрополь','\5191\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5225\http://tambov.egent.ru','Тамбов','\5225\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\http://vyshnij-volochek.egent.ru','Вышний Волочек','\3784\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\http://kashin.egent.ru','Кашин','\3784\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\http://ostashkov.egent.ru','Осташков','\3784\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\http://tver.egent.ru','Тверь','\3784\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\http://torzhok.egent.ru','Торжок','\3784\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\3784\http://toropets.egent.ru','Торопец','\3784\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5291\http://tomsk.egent.ru','Томск','\5291\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5326\http://tula.egent.ru','Тула','\5326\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5356\http://tobolsk.egent.ru','Тобольск','\5356\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5356\http://tyumen.egent.ru','Тюмень','\5356\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5404\http://izhevsk.egent.ru','Ижевск','\5404\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5432\http://ulyanovsk.egent.ru','Ульяновск','\5432\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5473\http://habarovsk.egent.ru','Хабаровск','\5473\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2499002\http://hanti-mansiysk.egent.ru','Ханты-Мансийск','\2499002\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2499002\http://nizhnevartovsk.egent.ru','Нижневартовск','\2499002\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\2499002\http://surgut.egent.ru','Сургут','\2499002\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5507\http://zlatoust.egent.ru','Златоуст','\5507\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5507\http://magnitogorsk.egent.ru','Магнитогорск','\5507\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5507\http://chelyabinsk.egent.ru','Челябинск','\5507\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5555\http://chita.egent.ru','Чита','\5555\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5600\http://cheboksari.egent.ru','Чебоксары','\5600\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5625\http://myshkin.egent.ru','Мышкин','\5625\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5625\http://rostov-velikij.egent.ru','Ростов Великий','\5625\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5625\http://rybinsk.egent.ru','Рыбинск','\5625\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5625\http://uglich.egent.ru','Углич','\5625\',2);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (4,'\5625\http://yaroslavl.egent.ru','Ярославль','\5625\',2);
COMMIT;

