CREATE TABLE IF NOT EXISTS SiteRegion(
SiteId INTEGER,
SiteRegionId VARCHAR,
SiteRegionTitle VARCHAR,
ParentId VARCHAR,
Level INTEGER,
PRIMARY KEY(SiteId,SiteRegionId));
BEGIN;
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/spb/','Санкт-Петербург','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/moskva/','Москва','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/moskovskaya-oblast/','Московская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/latvia/','Латвия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/krasnodar/','Краснодар','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/sochi/','Сочи','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/petrozavodsk/','Петрозаводск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kazan/','Казань','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/voronezh/','Воронеж','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/chelyabinsk/','Челябинск','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/adygea/','республика Адыгея','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/altai/','республика Алтай','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/altayskii-krai/','Алтайский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/amurskaya-oblast/','Амурская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/arhangelskaya-oblast/','Архангельская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/astrakhan-oblast/','Астраханская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/bashkortostan/','республика Башкортостан','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/belgorodskaya-oblast/','Белгородская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/bryanskaya-oblast/','Брянская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/buryatiya/','республика Бурятия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/vladimirskaya-oblast/','Владимирская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/volgogradskaya-oblast/','Волгоградская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/vologodskaya-oblast/','Вологодская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/voronezhskaya-oblast/','Воронежская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/zabaykalsky-krai/','Забайкальский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/ivanovskaya-oblast/','Ивановская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/irkutskaya-oblast/','Иркутская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/kabardino-balkaria/','республика Кабардино-Балкария','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kaliningradskaya-oblast/','Калининградская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kaluzhskaya-oblast/','Калужская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/kamchatka-krai/','Камчатский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/karachay-cherkessia/','республика Карачаево-Черкесия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kareliya/','республика Карелия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kemerovskaya-oblast/','Кемеровская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kirovskaya-oblast/','Кировская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/komi/','республика Коми','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kostromskaya-oblast/','Костромская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/krasnodarskii-krai/','Краснодарский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/krasnoyarskii-krai/','Красноярский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/kurskaya-oblast/','Курская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/lipetskaya-oblast/','Липецкая область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/magadan-oblast/','Магаданская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/mari-el/','республика Марий Эл','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/moskva/','Москва','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/moskovskaya-oblast/','Московская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/murmanskaya-oblast/','Мурманская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/nizhegorodskaya-oblast/','Нижегородская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/novgorodskaya-oblast/','Новгородская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/novosibirskaya-oblast/','Новосибирская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/omskaya-oblast/','Омская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/orenburgskaya-oblast/','Оренбургская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/orlovskaya-oblast/','Орловская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/penzenskaya-oblast/','Пензенская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/permskii-krai/','Пермский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/primorskii-krai/','Приморский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/pskovskaya-oblast/','Псковская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/rostovskaya-oblast/','Ростовская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/ryazanskaya-oblast/','Рязанская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/samarskaya-oblast/','Самарская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/spb/','Санкт-Петербург и Ленинградская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/saratovskaya-oblast/','Саратовская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/sakhalin-oblast/','Сахалинская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/sverdlovskaya-oblast/','Свердловская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/north-ossetia/','республика Северная Осетия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/smolenskaya-oblast/','Смоленская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/stavropolskii-krai/','Ставропольский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/tambovskaya-oblast/','Тамбовская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/tatarstan/','республика Татарстан','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/tverskaya-oblast/','Тверская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/tomskaya-oblast/','Томская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/tulskaya-oblast/','Тульская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/tyumenskaya-oblast/','Тюменская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/udmurtiya/','республика Удмуртия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/ulyanovskaya-oblast/','Ульяновская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/habarovskii-krai/','Хабаровский край','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/khanty-mansi-ao/','Ханты-Мансийский АО','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/chelyabinskaya-oblast/','Челябинская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/chuvashiya/','республика Чувашия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/regions/yamalo-nenets-ao/','Ямало-Ненецкий АО','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/yaroslavskaya-oblast/','Ярославская область','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/australia/','Австралия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/austria/','Австрия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/albania/','Албания','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/andorra/','Андорра','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/belize/','Белиз','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/belorussia/','Белоруссия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/belgium/','Бельгия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/bulgaria/','Болгария','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/great-britain/','Великобритания','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/hungary/','Венгрия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/germany/','Германия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/greece/','Греция','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/dominican-republic/','Доминиканская Республика','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/egypt/','Египет','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/israel/','Израиль','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/indonesia/','Индонезия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/iceland/','Исландия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/spain/','Испания','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/italy/','Италия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/canada/','Канада','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/caribbean-islands/','Карибские острова','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/cyprus/','Кипр','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\/latvia/','Латвия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/lithuania/','Литва','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/luxembourg/','Люксембург','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/maldives/','Мальдивы','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/morocco/','Марокко','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/monaco/','Монако','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/netherlands/','Нидерланды','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/norway/','Норвегия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/united-arab-emirates/','ОАЭ','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/paraguay/','Парагвай','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/poland/','Польша','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/portugal/','Португалия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/san-marino/','Сан-Марино','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/seychelles/','Сейшельские острова','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/serbia/','Сербия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/singapore/','Сингапур','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/slovakia/','Словакия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/slovenia/','Словения','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/usa/','США','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/thailand/','Таиланд','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/turkey/','Турция','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/ukraine/','Украина','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/finland/','Финляндия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/france/','Франция','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/croatia/','Хорватия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/montenegro/','Черногория','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/czech/','Чехия','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/switzerland/','Швейцария','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/sweden/','Швеция','\',1);
INSERT OR REPLACE INTO SiteRegion(SiteId,SiteRegionId,SiteRegionTitle,ParentId,Level) VALUES (6,'\http://prian.ru/estonia/','Эстония','\',1);
COMMIT;

